// <auto-generated />
namespace LinkarServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class changestodatamodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changestodatamodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201403121451010_changes to data models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
